POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "test 3",
    "author": "Tudor Orosz",
    "url": "www.testurl.com 3",
    "likes": 10,
    "userId": "6901c5ba7c4d0cbb25e81345"
}